import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import { EmpDetProvider } from "./components/context/EmpDetailContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black">
        <EmpDetProvider>
          <Navbar />
          {children}
        </EmpDetProvider>
      </body>
    </html>
  );
}
